apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: wanderlust
  labels:
    app: backend
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
      containers:
      - name: backend
        image: roshanx/wanderlust-backend:latest
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: backend-secrets
        - configMapRef:
            name: backend-config
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        resources:
          requests:
            cpu: "300m"
            memory: "256Mi"
          limits:
            cpu: "600m"
            memory: "512Mi"
---

apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: wanderlust
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 8080
  type: ClusterIP
