apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: wanderlust
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: roshanx/wanderlust-frontend-beta:v1
          ports:
            - containerPort: 5173
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: wanderlust
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - port: 5173         # inside cluster port
      targetPort: 5173 # container port
      nodePort: 31000  # external port on Node
      protocol: TCP
