apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: wanderlust
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongo
        image: mongo:6
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: gp2
      resources:
        requests:
          storage: 2Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: wanderlust
spec:
  clusterIP: None  # Required for StatefulSets to maintain DNS identity
  selector:
    app: mongodb
  ports:
  - port: 27017
    targetPort: 27017
