apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: wanderlust
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/redis
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
