pipeline {
    agent any

    parameters {
        string(name: 'FRONTEND_TAG', description: 'Frontend Docker Image Tag', defaultValue: 'latest')
        string(name: 'BACKEND_TAG', description: 'Backend Docker Image Tag', defaultValue: 'latest')
    }

    environment {
        GITHUB_CREDENTIALS = 'Github-cred'
        GITHUB_REPO = 'https://github.com/Roshanx96/wanderlust-mega-project.git'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git credentialsId: "${env.GITHUB_CREDENTIALS}", url: "${env.GITHUB_REPO}"
            }
        }

        stage('Verify: Docker Image Tags') {
            steps {
                script{
                    echo "FRONTEND_TAG: ${params.FRONTEND_TAG}"
                    echo "BACKEND_TAG: ${params.BACKEND_TAG}"
                }
            }
        }
        
        
        stage("Update: Kubernetes manifests"){
            steps{
                script{
                    dir('kubernetes'){
                        sh """
                            sed -i -e s/wanderlust-backend-beta.*/wanderlust-backend-beta:${params.BACKEND_TAG}/g backend.yaml
                        """
                    }
                    
                    dir('kubernetes'){
                        sh """
                            sed -i -e s/wanderlust-frontend-beta.*/wanderlust-frontend-beta:${params.FRONTEND_TAG}/g frontend.yaml
                        """
                    }
                    
                }
            }
        }

        stage('Commit and Push Changes') {
            steps {
                sh '''
                    git config user.email "jenkins@example.com"
                    git config user.name "Jenkins CI"
                    git add kubernetes/frontend.yaml kubernetes/backend.yaml
                    git commit -m "Update Kubernetes manifests with new Docker tags [CI/CD]"
                    git push origin main
                '''
            }
        }
    }

    post {
        success {
                 echo "✅ Wanderlust CD Pipeline Successful"
        }
        failure {
                 echo "❌ Wanderlust CD Pipeline Failed",

        }
    }
}
